export const USUARIO_CREADO = 'USUARIO_CREADO'
export const USUARIO_CREADO_EXITO = 'AGREAGAR_USUARIO_EXITO'
export const USUARIO_CREADO_ERROR = 'AGREAGAR_USUARIO_ERROR'

export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const OBTENER_USUARIO_EXITO = 'OBTENER_USUARIO_EXITO'
export const USUARIO_AUTH_ERROR = 'USUARIO_AUTH_ERROR'

export const USUARIO_LOGIN = 'USUARIO_LOGIN'
export const USUARIO_LOGIN_EXITO = 'USUARIO_LOGIN_EXITO'
export const USUARIO_LOGIN_ERROR = 'USUARIO_LOGIN_ERROR'

//Inmueble=products
//Creamos
export const PRODUCTS_CREADO = 'PRODUCTS_CREADO'
export const PRODUCTS_CREADO_EXITO = 'PRODUCTS_CREADO_EXITO'
export const PRODUCTS_CREADO_ERROR = '  PRODUCTS_CREADO_ERROR'
//mostramos
export const OBTENER_PRODUCTS = 'OBTENER_PRODUCTS'
export const OBTENER_PRODUCTS_EXITO = 'OBTENER_PRODUCTS_EXITO'
export const OBTENER_PRODUCTS_ERROR = 'OBTENER_PRODUCTS_ERROR'
//eliminamos
export const OBTENER_PRODUCTS_ELIMINAR = 'OBTENER_PRODUCTS_ELIMINAR'
export const PRODUCTS_ELIMINAR_EXITO = 'PRODUCTS_ELIMINAR_EXITO'
export const PRODUCTS_ELIMINAR_ERROR = 'PRODUCTS_ELIMINAR_ERROR'
//actualizamos
export const OBTENER_PRODUCTS_EDITAR = 'OBTENER_PRODUCTS_EDITAR'
export const COMENZAR_EDICION_PRODUCTS = 'COMENZAR_EDICION_PRODUCTS'
export const PRODUCTS_EDITADO_EXITO = 'PRODUCTS_EDITADO_EXITO'
export const PRODUCTS_EDITADO_ERROR = 'PRODUCTS_EDITADO_ERROR'
